### ISSUE TITLE
Missing english transcription

### ISSUE THREAD

**Issue by xrotwang** [UniversalDependencies/UD_Tupinamba-TuDeT#1]
Here https://github.com/UniversalDependencies/UD_Tupinamba-TuDeT/blob/8b238a7c378fd7e5e166566e7ef3bdd9e8a7ea32/tpn_tudet-ud-test.conllu#L217

**Comment by xrotwang** [comment]
@LanguageStructure could you fix this?

**Comment by LanguageStructure** [comment]
are you using dev or master?

**Comment by xrotwang** [comment]
dev. That's where the linked sentence is on.
