### ISSUE TITLE
Duplicate sentence ID

### ISSUE THREAD

**Issue by xrotwang** [UniversalDependencies/UD_Tupinamba-TuDeT#2]
`sent_id = 6` appears twice:
- https://github.com/UniversalDependencies/UD_Tupinamba-TuDeT/blob/a20518a93ad6acd17d1c7356fc1f4b09b539a6a5/tpn_tudet-ud-test.conllu#L66
- https://github.com/UniversalDependencies/UD_Tupinamba-TuDeT/blob/a20518a93ad6acd17d1c7356fc1f4b09b539a6a5/tpn_tudet-ud-test.conllu#L285

**Comment by xrotwang** [comment]
Can you look into this, @LanguageStructure ?

**Comment by LanguageStructure** [comment]
just changed it on dev
