### ISSUE TITLE
Token without head

### ISSUE THREAD

**Issue by wellington36** [UniversalDependencies/UD_Tupinamba-TuDeT#5]
In branch dev, we have a token without head: https://github.com/UniversalDependencies/UD_Tupinamba-TuDeT/blob/be4a46c3ff44b7eebe104e324386e1e86f24ca7a/tpn_tudet-ud-test.conllu#L4189

@LanguageStructure

**Comment by LanguageStructure** [comment]
corrigido no dev:


17	,	,	PUNCT	punct	_	12	punct	12:punct	_
